"""empty message

Revision ID: 3f504581ca2b
Revises: 642ba4b55c52
Create Date: 2022-08-10 21:52:50.144445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f504581ca2b'
down_revision = '642ba4b55c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biological__age', sa.Column('edad_chrono', sa.Integer(), nullable=False))
    op.add_column('biological__age', sa.Column('longev_hist', sa.String(length=30), nullable=False))
    op.add_column('biological__age', sa.Column('albumina', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('creatinina', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('glucosa', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('Porct_linfoc', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('MCV', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('AD_glób_Red', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('fosfatasa_alc', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('globulos_bl', sa.String(), nullable=False))
    op.add_column('biological__age', sa.Column('PC_React', sa.String(), nullable=False))
    op.drop_column('biological__age', 'longe_hist')
    op.drop_column('biological__age', 'edad')
    op.drop_column('biological__age', 'blood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biological__age', sa.Column('blood', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('biological__age', sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('biological__age', sa.Column('longe_hist', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('biological__age', 'PC_React')
    op.drop_column('biological__age', 'globulos_bl')
    op.drop_column('biological__age', 'fosfatasa_alc')
    op.drop_column('biological__age', 'AD_glób_Red')
    op.drop_column('biological__age', 'MCV')
    op.drop_column('biological__age', 'Porct_linfoc')
    op.drop_column('biological__age', 'glucosa')
    op.drop_column('biological__age', 'creatinina')
    op.drop_column('biological__age', 'albumina')
    op.drop_column('biological__age', 'longev_hist')
    op.drop_column('biological__age', 'edad_chrono')
    # ### end Alembic commands ###
