"""empty message

Revision ID: 642ba4b55c52
Revises: f0289c3bee97
Create Date: 2022-08-09 19:29:14.144675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642ba4b55c52'
down_revision = 'f0289c3bee97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biological__age',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexo_genero', sa.String(length=30), nullable=False),
    sa.Column('blood', sa.String(length=50), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('raza_etni', sa.String(length=30), nullable=False),
    sa.Column('longe_hist', sa.String(length=30), nullable=False),
    sa.Column('frec_vida_sexual', sa.String(), nullable=False),
    sa.Column('agudeza_visual', sa.String(), nullable=False),
    sa.Column('peso_corporal', sa.String(), nullable=False),
    sa.Column('med_cintura', sa.Integer(), nullable=False),
    sa.Column('med_ante_brazo', sa.Integer(), nullable=False),
    sa.Column('ta_cardio', sa.String(), nullable=False),
    sa.Column('colest_ldl', sa.String(), nullable=False),
    sa.Column('colest_hdl', sa.String(), nullable=False),
    sa.Column('fumador', sa.String(), nullable=False),
    sa.Column('i_masa_corporal', sa.String(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('result_telomeros', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('age__biological')
    op.add_column('cuidador', sa.Column('password', sa.String(length=50), nullable=False))
    op.drop_constraint('paciente_blood_key', 'paciente', type_='unique')
    op.drop_column('paciente', 'blood')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('blood', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('paciente_blood_key', 'paciente', ['blood'])
    op.drop_column('cuidador', 'password')
    op.create_table('age__biological',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fumador', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('masa_corporal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('vida_sexual', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('paciente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], name='age__biological_paciente_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='age__biological_pkey')
    )
    op.drop_table('biological__age')
    # ### end Alembic commands ###
