"""empty message

Revision ID: f0289c3bee97
Revises: 
Create Date: 2022-08-04 23:40:26.298661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0289c3bee97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuidador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('blood', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood'),
    sa.UniqueConstraint('email')
    )
    op.create_table('age__biological',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fumador', sa.Boolean(), nullable=False),
    sa.Column('masa_corporal', sa.Boolean(), nullable=False),
    sa.Column('vida_sexual', sa.Boolean(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('age__biological')
    op.drop_table('paciente')
    op.drop_table('cuidador')
    # ### end Alembic commands ###
